# Generated by Django 5.0 on 2023-12-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.CharField(default='http://www.energyfit.com.mk/wp-content/plugins/ap_background/images/default/default_1.png', max_length=500),
        ),
    ]
